services:
  database:
    container_name: docker_and_symfony_database
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/x86_64
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: docker_and_symfony
      MYSQL_DATABASE: docker_and_symfony
      MYSQL_USER: docker_and_symfony
      MYSQL_PASSWORD: docker_and_symfony
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: docker_and_symfony_php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/docker_and_symfony
    depends_on:
      - database
  nginx:
    container_name: docker_and_symfony_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/docker_and_symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database